// Copyright (C) 2026 International Digital Economy Academy
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; version 2.1
// of the License.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library.  If not, see <https://www.gnu.org/licenses/>.

///|
const TOK_AND : Int = @arm64.TOK_AND

///|
const TOK_EQ : Int = @arm64.TOK_EQ

///|
const TOK_GE : Int = @arm64.TOK_GE

///|
const TOK_GT : Int = @arm64.TOK_GT

///|
const TOK_LE : Int = @arm64.TOK_LE

///|
const TOK_LT : Int = @arm64.TOK_LT

///|
const TOK_NE : Int = @arm64.TOK_NE

///|
const TOK_SAR : Int = @arm64.TOK_SAR

///|
const TOK_SHL : Int = @arm64.TOK_SHL

///|
const TOK_SHR : Int = @arm64.TOK_SHR
