///|
const TOK_AND : Int = @arm64.TOK_AND

///|
const TOK_EQ : Int = @arm64.TOK_EQ

///|
const TOK_GE : Int = @arm64.TOK_GE

///|
const TOK_GT : Int = @arm64.TOK_GT

///|
const TOK_LE : Int = @arm64.TOK_LE

///|
const TOK_LT : Int = @arm64.TOK_LT

///|
const TOK_NE : Int = @arm64.TOK_NE

///|
const TOK_SAR : Int = @arm64.TOK_SAR

///|
const TOK_SHL : Int = @arm64.TOK_SHL

///|
const TOK_SHR : Int = @arm64.TOK_SHR
